# DC1 Tenants Networks
# Documentation of Tenant specific information - Vlans/VRFs
# SVI Profile
svi_profiles:
  GENERIC:
    mtu: 1560
    enabled: true
  GENERIC_FULL:
    name: GENERIC Name
    mtu: 1560
    enabled: false
    ip_address_virtual: 10.1.10.254/24
  WITH_NO_MTU:
    enabled: true
  WITH_DHCP_AND_SNOOPING:
    enabled: true
    ip_address_virtual: 10.1.11.254/24
    igmp_snooping_enabled: false
    ip_helpers:
      1.1.1.1:
        source_interface: lo100
        source_vrf: TEST
  WITH_DHCP:
    enabled: true
    ip_helpers:
      1.1.1.1:
        source_interface: lo100
        source_vrf: MGMT


tenants:
  # Tenant_A Specific Information - VRFs / VLANs
  Tenant_A:
    mac_vrf_vni_base: 10000
    vrfs:
      Tenant_A_OP_Zone:
        vrf_vni: 10
        vtep_diagnostic:
          loopback: 100
          loopback_ip_range: 10.255.1.0/24
        svis:
          # SVI as string
          '110':
            name: Tenant_A_OP_Zone_1
            tags: ['opzone']
            enabled: True
            ip_address_virtual: 10.1.10.1/24
          # SVI as integer
          111:
            vni_override: 50111
            name: Tenant_A_OP_Zone_2
            tags: ['opzone']
            enabled: True
            ip_address_virtual: 10.1.11.1/24
            ip_helpers:
              1.1.1.1:
                source_interface: lo100
                source_vrf: MGMT
      Tenant_A_WEB_Zone:
        vrf_vni: 11
        svis:
          120:
            name: Tenant_A_WEB_Zone_1
            tags: ['web', 'erp1']
            profile: WITH_DHCP_AND_SNOOPING
            ip_address_virtual: 10.1.20.1/24
            ip_address_virtual_secondaries:
              - 10.2.20.1/24
              - 10.2.21.1/24
          121:
            name: Tenant_A_WEBZone_2
            tags: ['web']
            profile: GENERIC_FULL
      Tenant_A_APP_Zone:
        vrf_vni: 12
        svis:
          130:
            name: Tenant_A_APP_Zone_1
            tags: ['app', 'erp1']
            profile: WITH_NO_MTU
            ip_address_virtual: 10.1.30.1/24
          131:
            name: Tenant_A_APP_Zone_2
            tags: ['app']
            enabled: True
            ip_address_virtual: 10.1.31.1/24
          132:
            name: Tenant_A_APP_Zone_3
            tags: ['erp2']
            enabled: True
            nodes:
              DC1-LEAF1A:
                ip_address: 10.1.32.1/24
            ip_virtual_router_addresses:
              - 10.1.32.254
              - 10.2.32.254/24
              - 10.3.32.254/24
      Tenant_A_DB_Zone:
        vrf_vni: 13
        svis:
          140:
            name: Tenant_A_DB_BZone_1
            tags: ['db', 'erp1']
            enabled: True
            ip_address_virtual: 10.1.40.1/24
          141:
            name: Tenant_A_DB_Zone_2
            tags: ['db']
            enabled: True
            ip_address_virtual: 10.1.41.1/24
      Tenant_A_WAN_Zone:
        vrf_id: 14
        ospf:
          enabled: true
          max_lsa: 15000
          redistribute_bgp:
            enabled: true
          nodes:
            - DC1-BL1A
            - DC1-BL1B
        l3_interfaces:
          - interfaces: [Ethernet7]
            ip_addresses: [10.10.10.10/24]
            nodes: [DC1-BL1A]
            mtu: 9000
            enabled: True
            description: "test"
            ospf:
              enabled: true
              area: 0
              cost: 100
              authentication: message-digest
              point_to_point: true
              message_digest_keys:
                - id: 1
                  hash_algorithm: sha1
                  key: "AQQvKeimxJu+uGQ/yYvv9w=="
                - id: 2
                  key: "AQQvKeimxJu+uGQ/yYvv9w=="
          - interfaces: [Ethernet7]
            ip_addresses: [10.10.20.20/24]
            nodes: [DC1-BL1B]
            mtu: 9000
            enabled: True
            description: "test"
        static_routes:
          - destination_address_prefix: 10.3.4.0/24
            gateway: 1.2.3.4
            nodes: [DC1-BL1A, DC1-BL1B]
        bgp_peers:
          123.1.1.10:
            remote_as: 1234
            password: "AQQvKeimxJu+uGQ/yYvv9w=="
            description: External IPv4 BGP peer
            send_community: standard extended
            maximum_routes: 0
            default_originate:
              always: false
            update_source: Loopback123
            ebgp_multihop: 3
            nodes: [DC1-BL1A, DC1-BL1B]
            set_ipv4_next_hop: 123.1.1.1
            route_map_in: RM-123-1-1-10-IN
            # we don't expect this in the output, next_hop takes precedence
            route_map_out: RM-123-1-1-10-OUT
            local_as: 123
          123.1.1.11:
            remote_as: 1234
            password: "AQQvKeimxJu+uGQ/yYvv9w=="
            description: External IPv4 BGP peer
            send_community: standard extended
            maximum_routes: 0
            default_originate:
              always: false
            update_source: Loopback123
            ebgp_multihop: 3
            nodes: [DC1-BL1A, DC1-BL1B]
            route_map_in: RM-123-1-1-11-IN
            route_map_out: RM-123-1-1-11-OUT
            local_as: 123
          fd5a:fe45:8831:06c5::a:
            remote_as: 12345
            send_community: all
            nodes: [DC1-BL1A, DC1-BL1B]
            set_ipv6_next_hop: fd5a:fe45:8831:06c5::1
          fd5a:fe45:8831:06c5::b:
            remote_as: 12345
            nodes: [DC1-BL1A, DC1-BL1B]
        svis:
          150:
            name: Tenant_A_WAN_Zone_1
            tags: ['wan']
            enabled: True
            ip_address_virtual: 10.1.40.1/24
            ospf:
              enabled: true
              area: 1
              cost: 100
              authentication: simple
              simple_auth_key: "AQQvKeimxJu+uGQ/yYvv9w=="
        additional_route_targets:
          - type: import
            address_family: vpn-ipv4
            route_target: '65000:123'
            nodes: [ DC1-BL1A, DC1-BL1B ]
          - type: export
            address_family: vpn-ipv4
            route_target: '65000:123'
            nodes: [ DC1-BL1A, DC1-BL1B ]
          - type: import
            address_family: evpn
            route_target: '65000:456'
            # nodes not set - so all devices should get this additional route target
          - type: export
            address_family: evpn
            route_target: '65000:789'
            # nodes not set - so all devices should get this additional route target
      Tenant_L3_VRF_Zone:
        vrf_vni: 15
        l3_interfaces:
          - interfaces: [ Ethernet8, Ethernet9, Ethernet8, Ethernet9 ]
            ip_addresses: [10.10.10.10/24, 10.10.20.20/24, 10.10.30.10/24, 10.10.40.20/24]
            nodes: [DC1-BL1A, DC1-BL1A, DC1-BL1B, DC1-BL1B]
            mtu: 9000
            enabled: True
            description: "test"
    l2vlans:
      # L2 vlan as string
      '160':
        name: Tenant_A_VMOTION
        tags: ['opzone']
      # L2 vlan as integer
      161:
        name: Tenant_A_NFS
        tags: ['opzone']
  # Tenant_B Specific Information - VRFs / VLANs
  Tenant_B:
    mac_vrf_vni_base: 20000
    vrfs:
      Tenant_B_OP_Zone:
        vrf_vni: 20
        svis:
          210:
            name: Tenant_B_OP_Zone_1
            tags: ['opzone']
            enabled: True
            ip_address_virtual: 10.2.10.1/24
          211:
            name: Tenant_B_OP_Zone_2
            tags: ['opzone']
            enabled: True
            ip_address_virtual: 10.2.11.1/24
      Tenant_B_WAN_Zone:
        vrf_vni: 21
        svis:
          250:
            name: Tenant_B_WAN_Zone_1
            tags: ['wan']
            enabled: True
            ip_address_virtual: 10.2.50.1/24
  # Tenant_C Specific Information - VRFs / VLANs
  Tenant_C:
    mac_vrf_vni_base: 30000
    vrfs:
      Tenant_C_OP_Zone:
        vrf_vni: 30
        enable_mlag_ibgp_peering_vrfs: true
        mlag_ibgp_peering_vlan: 2
        svis:
          310:
            name: Tenant_C_OP_Zone_1
            tags: ['opzone']
            enabled: True
            ip_address_virtual: 10.3.10.1/24
          311:
            name: Tenant_C_OP_Zone_2
            tags: ['opzone']
            enabled: True
            ip_address_virtual: 10.3.11.1/24
      Tenant_C_WAN_Zone:
        vrf_vni: 31
        svis:
          350:
            name: Tenant_C_WAN_Zone_1
            tags: ['wan']
            enabled: True
            ip_address_virtual: 10.3.50.1/24
